version: "3.7"

services: 
    app:
        image: node:12
        container_name: jukebox
        restart: unless-stopped
        working_dir: /app
        volumes: 
            - ./:/app
        ports: 
            - 8080:8080
        command: sh -c "npm install && npm run serve"